#+TITLE: Advanced Microeconomics II (research track)
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil
#+Latex_Header: \usepackage{natbib}
* News
- PhD students who cannot register for the exam through Klips should write me an email with their full name and their student number before June 03 in order to register.
- There are no lectures on May 21 (Monday) and May 23 (Wednesday) due to the pentecost break.
- I would be interested in feedback. In particular concerning overlap with other courses, the level of the course, (mis-)match with expectations etc.
- Registration for the exam is now possible in KLIPS.
- Exam date: July 18, 10:00-11:00 
* Material
- Exercises: [[./exercises.tex][tex]] [[https://github.com/schottmueller/advMicro/files/2044518/exercises.pdf][pdf]]
- Slides:
  - [[https://github.com/schottmueller/advMicro/files/1890670/dominRatio.pdf][Dominance and rationalizability]]
  - [[https://github.com/schottmueller/advMicro/files/1888753/NashEq.pdf][Nash Theorem]]
  - [[https://github.com/schottmueller/advMicro/files/1890677/corrEq.pdf][correlated eq.]]
  - [[https://github.com/schottmueller/advMicro/files/1927713/BNE.pdf][BNE]]
  - [[https://github.com/schottmueller/advMicro/files/1960716/auctions.pdf][auctions]]
  - [[https://github.com/schottmueller/advMicro/files/1966289/spne.pdf][SPNE]]
  - [[https://github.com/schottmueller/advMicro/files/1987255/pbe.pdf][PBE]]
  - [[https://github.com/schottmueller/advMicro/files/2000878/signal.pdf][signaling]]
  - [[https://github.com/schottmueller/advMicro/files/1994283/cheapTalk.pdf][cheap talk]]
  - [[https://github.com/schottmueller/advMicro/files/2044522/revelationPrinc.pdf][revelation principle]]
  - [[https://github.com/schottmueller/advMicro/files/2044524/domStratMechDes.pdf][dominant strat. implementation]]
- Handouts etc.:
  - [[https://github.com/schottmueller/advMicro/files/1954228/math.pdf][math handout]]
* Prerequisites
I assume that you have some introductory knowledge of game theory on the level of cite:gibbons1992primer. In particular, you should know the material in chapters 1 and 2 in Gibbons' book (strategic form games, dominance, mixed strategies, mixed and pure Nash equilibrium, extensive form games, game trees, backwards induction, subgame perfect Nash equilibrium) and be able to apply it in simple games. From Advanced Microeconomics I, we built upon the part about /decision making under uncertainty/ (expected utility theorem). In terms of mathematics, it is helpful if you master the material of the course /Advanced Mathematics for Economists/. Having said that, most of the used math tools will not be far beyond high school maths. At the minimum you have to know (partial) differentiation, integration and optimization of functions and basic statistics (discrete and continuous probability distributions, expected values as well as Bayes' rule and conditional probabilities). Ideally, you should also have some idea of what a mathematical proof is.

* Plan
We have 15*2=30 meetings. The idea is to have 20 lectures and 10 exercise classes, i.e. every third class we talk about exercises dealing with the material of the two previous lectures. /You are expected to have tried to solve the exercises beforehand/ (and hopefully you succeeded with some of them), i.e. in the exercise classes we deal with your questions and problems and we are /not/ solving the exercises there from scratch.

* Books

Most material is covered in cite:mas1995microeconomic which is abbreviated MWG in the following. Roughly speaking, we will cover chapters 8, 9, 13 and 23 from this book and -- as time permits -- add a few papers on topics not covered in MWG towards the end of the course.

Some other interesting books on game theory covering the course material partially are
- cite:fudenberg1991game (FT): Covers an impressive amount of material in considerable depth at PhD level. Some of the proofs are, however, not fully worked out.
- cite:maschler2013game (MSZ): Impresses with very clear proofs and fully worked out examples. Do, however, not expect to find much economics in this book.
- cite:osborne1994course (OR). A very nice book that is freely available for download from the authors' websites. 

For mechanism design, cite:boergers2015 is an excellent source which naturally covers much more than we do in the course.

* Schedule

The following plan is...well a plan...and as such it might be adapted to unforseen circumstances if necessary.

** Static games of complete information I
- iterative elimination of strictly dominated strategies (MWG 8.B)
- rationalizability (MWG 8.C)

** Static games of complete information II
- mixed strategy Nash equilibrium (MWG 8.D)
- Brouwer's fixed point theorem and existence of Nash equilibrium (MSZ 5.3; MWG 8.Appendix gives a proof using Kakutani's fixed point theorem)

** Static games of complete information III
- correlated equilibrium (MSZ 8)
** Static games of incomplete information I
- Bayesian Nash equilibrium (MWG 8.E)
- simple examples of BNE
# - purification 

** Static games of incomplete information II: Auctions
- first price auction (Gibbons 3.2B or MWG Example 23.B.5)
- second price auction (MWG Example 23.B.6)
- common value auction 
- futher not required reading: if you are interested in experiments: Ngangoue and Weizsäcker "Learning from unrealized versus realized prices", [[https://www.wiwi.hu-berlin.de/de/professuren/vwl/microeconomics/people/gweizsaecker/paper_gweizsaecker_learningprice.pdf][working paper]], 2018); a detailled source for what we did is Krishna's book "Auction Theory" (academic Press 2010), chapter 2 and 6.
# - double auction (Gibbons 3.2C or FT Example 6.4 p. 219)

# ** Common knowledge I
# - common knowledge
# - Rubinstein's email game

# ** Common knowledge II: Global games
# - stag hunt
# - global games

** Dynamic games I
- backwards induction and subgame perfect equilibrium (MWG 9.A and 9.B)
- one deviation principle (MWG 9.B)
- Rubinstein bargaining  (MWG 9.Appendix A)
- forward induction (MWG 9.D)

** Dynamic games II
- beliefs and sequential rationality (MWG 9.C)
- perfect Bayesian equilibrium (MWG 9.C)
- sequential equilibrium (MWG 9.C)
- alternative not required reading: OR ch. 12  is a well written piece on the issues mentioned in the lecture; OR ch. 11 covers some more foundational issues that we skipped

** Signaling and refinements
- Spence signaling model (MWG 13.C and MWG 13.Appendix)

# ** Adverse selection
# - Akerlof's lemons market (MWG 13.B)
# - Rothschild-Stiglitz insurance market (cite:rothschild1976equilibrium)

** Cheap talk
- Crawford and Sobel (cite:crawford1982cheap)
- further not required reading: see the [[https://doi.org/10.1057/978-1-349-95189-5_2525][article]] in the New Palgrave Dictionary of Economics on Cheap Talk for a quick overview over the literature, for more on the delegation example see Alonso, Ricardo, and Niko Matouschek. "Optimal delegation." Review of Economic Studies 75.1 (2008): 259-293. (and several other papers by these authors)
** Mechanism design I: revelation principle
- mechanism design problem (MWG 23.B)
- revelation principle (MWG 23.B)

** Mechanism design II: dominant strategy implementation
# - Gibbard Satterthwaite theorem (MWG 23.C)
- Vickrey-Clarke-Groves mechanism (MWG 23.C)

# ** Mechanism design III: AGV
# - Bayesian implementation (MWG 23.D)
# - expected externality mechanism (MWG 23.D up to p. 887)

** Mechanism design III: Myerson- Satterthwaite
- Bayesian implementation (MWG 23.D)
- envelope theorem (MWG 23.D p. 887-889)
- Myerson-Satterthwaite theorem (MWG 23.E)

** Mechanism design IV: screening
- non-linear pricing by a monopolist (cite:maskin1984monopoly)

** Mechanism design V: optimal auctions
- revenue equivalence (MWG 23.D p.889-)
- optimal independent, private value auctions (MWG Example 23.F.2)

** Mechanism design VI: correlated information
 - belief extraction
 - Cremer-McLean mechanism (cite:cre88)

** Information design I: Bayesian persuasion
- Bayes correlated equilibrium (cite:bergemann16_infor_desig_bayes_persuas_bayes_correl_equil)
- Bayesian persuasion (cite:bergemann17_infor_desig, cite:kamenica11_bayes_persuas)

** Information design II: interlude
 - value of information in experimentation
 - stochastic dominance orderings
 # - Blackwell's theorem (cite:blackwell53)

** Information design III: combined information and mechanism design
- recent paper, e.g. cite:roe17

bibliographystyle:chicago
bibliography:/home/christoph/stuff/bibliography/references.bib
