#+TITLE:    Optimal mechanism in bilateral trade + Limit results
#+AUTHOR:    Christoph Schottmüller
#+EMAIL:     christoph@worknotebook.home
#+DATE:      
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport


#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]
#+BEAMER_FRAME_LEVEL: 2
#+latex_header: \mode<beamer>{\useinnertheme{rounded}\usecolortheme{rose}\usecolortheme{dolphin}\setbeamertemplate{navigation symbols}{}\setbeamertemplate{footline}[frame number]{}}
#+latex_header: \mode<beamer>{\usepackage{amsmath,amssymb}\usepackage{ae,aecompl}}

* Optimal mechanism in bilateral trade
** Optimal mechanism in bilateral trade I
- Myerson-Satterthwaite setup
- for simplicity: $c$ and $v$ are uniformly distributed on $[0,1]$
- envelope theorem:
  - $U_S(c)=U_S(1)+\int_c^1 \mathbb{E}_v[y(v,x)] \,dx$ \vspace*{0.2cm}\linebreak\vspace*{0.2cm} $\Rightarrow$ $T_S(c) = U_S(1)+\int_c^1 \mathbb{E}_v[y(v,x)] \,dx+ \mathbb{E}_v[y(v,c)]c$
  - $U_B(v)=U_B(0)+\int_0^v \mathbb{E}_c[y(x,c)] \,dx$ \vspace*{0.2cm}\linebreak\vspace*{0.2cm} $\Rightarrow$ $T_B(v) = v\mathbb{E}_c[y(x,c)]  - U_B(0)-\int_0^v \mathbb{E}_c[y(x,c)] \,dx$
- budget constraint (in ex ante form): $$\int_{0}^{1} U_{S}(1)+\int_{c}^{1} \mathbb{E}_{v}[y(v,x)]\, dx+ \mathbb{E}_{v}[y(v,c)]c\; dc$$    $$\leq \int_{0}^{1} v\mathbb{E}_{c}[y(x,c)]  - U_{B}(0)-\int_{0}^{v} \mathbb{E}_{c}[y(x,c)] \;dx\; dv$$

** Optimal mechanism in bilateral trade II
- budget constraint (in ex ante form):$$\int_{0}^{1} U_{S}(1)+\int_{c}^{1} \mathbb{E}_{v}[y(v,x)]\, dx+ \mathbb{E}_{v}[y(v,c)]c\; dc$$    $$\leq \int_{0}^{1} v\mathbb{E}_{c}[y(x,c)]  - U_{B}(0)-\int_{0}^{v} \mathbb{E}_{c}[y(x,c)] \;dx\; dv$$
- use integration by parts to eliminate double integrals:
$$U_S(1)+\int_0^1 2\mathbb{E}_v[y(v,c)]c \;dc\leq -U_B(0)+ \int_0^1 \mathbb{E}_c[y(v,c)] (2v-1)\;dv$$
$$U_S(1)+U_B(0)\leq  \int_0^1\int_0^1 y(v,c) (2v-1-2c)\;dv\; dc$$

** Optimal mechanism in bilateral trade II
- objective:\linebreak $\int_0^1\int_0^1 y(v,c)(v-c)\;dv\;dc$
- constraints:
  - budget balance: \linebreak $U_S(1)+U_B(0)\leq  \int_0^1\int_0^1 y(v,c) (2v-1-2c)\;dv\; dc$
  - monotonicity: 
     - $\mathbb{E}_v[y(v,c)]$ non-increasing in $c$
     - $\mathbb{E}_c[y(v,c)]$ non-decreasing in $v$
  - participation:
     - $U_S(1)\geq 0$
     - $U_B(0)\geq 0$
  - feasibility: $0\leq y(v,c)\leq 1$
- variables: $y$, $U_S(1)$, $U_B(0)$

\vspace*{0.5cm}

- what is optimal $U_S(1)$, $U_B(0)$?

** Optimal mechanism in bilateral trade III
- Lagrangian relaxed problem:
$$\mathcal{L}(y,\lambda)=\int_0^1\int_0^1 y(v,c)\left(v-c+\lambda (2v-2c-1)  \right)\;dv\;dc$$

- $\max_y \mathcal{L}$:
$$y^*(v,c)=\begin{cases}1 &\text{ if }v-c\geq \lambda/(1+2\lambda)\\ 0 & \text{ else} \end{cases}$$

- $\lambda$ such that budget balance constraint holds with equality:
$$\int_0^{1-\lambda/(1+2\lambda)}\int_{c+\lambda/(1+2\lambda)}^1  (2v-1-2c)\;dv\; dc=0$$

$\Leftrightarrow \frac{\lambda}{1+2\lambda}=1/4$ $\quad\Rightarrow\quad y^*(v,c)=\begin{cases}1 &\text{ if }v-c\geq 1/4\\ 0 & \text{ else} \end{cases}$

- monotonicity: $\checkmark$ 

** Optimal mechanism in bilateral trade IV
- "second best": trade if and only if $v-c\geq 1/4$
- compare to equilibrium in linear strategies of the double auction (exercise 2c for lecture 5)

* Trade with many buyers and sellers
** Many buyers and sellers: setup
- $n$ buyers and $m$ sellers
- buyer $i$ has unit demand and valuation $v_i$ (private information)
- seller $i$ has unit supply and costs $c_i$ (private information)
\vspace*{1cm}
- which trades are efficient?


** Many buyers and sellers: efficiency
- order valuations (relabeling buyers if necessary): $v_1\geq v_2\geq\dots\geq v_n$
- order costs (relabeling sellers if necessary): $c_1\leq c_2\leq\dots\leq c_m$
- draw supply and demand
# efficient let k be such that $v_k\geq c_k$ but $v_{k+1}<c_{k+1}$; efficiency is that buyer 1 to k trade with seller 1 to k

** Many buyers and sellers: almost efficient trade
- let k be such that $v_k\geq c_k$ but $v_{k+1}<c_{k+1}$
  - efficiency: buyers 1 to $k$ trade with sellers 1 to $k$
- "almost efficient mechanism":
  - buyers 1 to $k-1$ trade with sellers 1 to $k-1$ 
  - buyers pay price $v_k$, sellers receive $c_k$
- show: almost efficient mechanism is (dominant strategy!) incentive compatible and produces budget surplus
- assume that $v_i\sim \Phi$ with strictly positive density on support $[a,b]$
- assume that $c_i\sim \Psi$ with strictly positive density on support $[c,d]$ with $[a,b]\cap[c,d]\neq\emptyset$
*** 
Efficiency in almost efficient mechanism is arbitrarily close to first best efficiency as $m,n\rightarrow\infty$.

* Public good problem with many players
** Public good problem with many players: setting
- public good is either provided, $x=1$, or not, $x=0$
- $I$ players with private valuation $\theta_i$
- $\theta_i$ are independently uniformly distributed on $[0,1]$
- costs of public good are $cI$ with $0<c<1$
- outside option: 0

\vspace*{0.2cm}
- direct mechanism: $(x(\theta),t_i(\theta))$ 
- participation constraint: $U_i(\theta_i)=X_i(\theta_i)\theta_i-T_i(\theta_i)\geq 0$
- ex ante budget balance: $\mathbb{E}_\theta\left[\sum_i t_i(\theta)\right]\geq \mathbb{E}_\theta[x(\theta)]cI$ 

** IC
- incentive compatibility is equivalent to
  - envelope theorem: $U(\theta_i)=\int_0^{\theta_i}X_i(s)\,ds$
  - monotonicity: $X_i$ increasing in $\theta_i$

** budget balance I
$$\mathbb{E}_\theta\left[\sum_i t_i(\theta)\right]\geq \mathbb{E}_\theta[x(\theta)]cI$$
$$\Leftrightarrow \sum_i \int_0^1 T_i(\theta_i)\,d\theta_i\geq\mathbb{E}_\theta[x(\theta)]cI$$
$$\Leftrightarrow \sum_i \int_0^1 X_i(\theta_i)\theta_i-U_i(\theta_i)\,d\theta_i\geq\mathbb{E}_\theta[x(\theta)]cI$$
$$\Leftrightarrow \sum_i \int_0^1 X_i(\theta_i)\theta_i-\int_0^{\theta_i}X_i(s)\,ds\,d\theta_i\geq\mathbb{E}_\theta[x(\theta)]cI$$
$$\Leftrightarrow \sum_i \int_0^1 X_i(\theta_i)(2\theta_i-1)\,d\theta_i\geq\sum_i\mathbb{E}_\theta[x(\theta)]c$$
$$\Leftrightarrow \mathbb{E}_\theta\left[ \sum_i x(\theta)(2\theta_i-1-c)\right]\geq 0$$
# $$\Leftrightarrow \sum_i \int_0^1 X_i(\theta_i)(2\theta_i-1-c)\,d\theta_i\geq0$$
** budget balance II
$$\Leftrightarrow \mathbb{E}_\theta\left[I x(\theta)\sum_i (2\theta_i-1-c)/I\right]\geq 0$$

- as $I\rightarrow\infty$,  $(\sum_i (2\theta_i-1-c))/I$ converges to $\mathbb{E}_{\theta_i}[2\theta_i-1-c]$ 
# (independence of $\theta_i$ and law of large numbers)
- $\mathbb{E}_{\theta_i}[2\theta_i-1-c]< 0$ 
# as $\theta_i\sim u[0,1]$ and $c>0$

- in the limit budget balance holds only if $x(\theta)=0$ with probability 1

- in the limit, $\sum_i \theta_i-c$ is strictly positive with probability 1 if $c<1/2$

- large number of players amplify the free-rider problem
* Optimal provision of a public good
** Public good: Welfare maximizing mechanism
$$\max_x\mathbb{E}_\theta\left[ x(\theta)\sum_i\{\theta_i-c\} \right]$$
$$ s.t.:\quad  \mathbb{E}_\theta\left[ \sum_i x(\theta)(2\theta_i-1-c)\right]\geq 0$$

$$\mathcal{L}=\mathbb{E}_\theta\left[ x(\theta)\sum_i\{\theta_i-c+\lambda(2\theta_i-1-c)\} \right]$$

$$x^*(\theta)=\begin{cases} 1 &\sum_i \theta_i-c\geq\frac{\lambda}{1+\lambda}\sum_i 1-\theta_i \\ 0 & \text{else}\end{cases}$$
$\lambda^*$ such that budget balance constraint holds with equality 
 
** Public good: Welfare maximizing mechanism example

- for $c=1/4$ (all values are rounded):
|   I | $\lambda/(1+\lambda)$ | prob $x^*=1$ | prob $x^{fb}=1$ |
|-----+-----------------------+--------------+-----------------|
| /   |                   <  |           < |               < |
|   2 |                  0.31 |         0.63 |            0.88 |
|   3 |                  0.45 |         0.54 |            0.93 |
|   4 |                  0.54 |         0.46 |            0.96 |
|   5 |                   0.6 |         0.4  |            0.97 |
|  10 |                  0.76 |         0.21 |     $\approx 1$ |


* Addendum
** Why ex ante BB is equivalent to ex post BB I
We used the ex ante budget balance: In expectation, the transfer the seller receives equals the transfer the buyer pays. The expected transfer of the citizens equals the costs of the public good times the probability that it is carried out. Ex post budget balance means that the budget is balanced for every single type vector. Clearly, ex post budget balance implies ex ante budget balance.

For the setting with quasi-linear utility and independent types that we looked at here, there is a general result that says: If we have a direct mechanism that is incentive compatible, (satisfies participation constraints), and ex ante budget balanced, then there are transfers that maintain the properties of this mechanism (incentive compatibility, participation constraints, same allocation for every type vector) but add ex post budget balance.

** Why ex ante BB is equivalent to ex post BB II

\begin{footnotesize}The proof is as follows: Take the public good setting for concreteness and take some mechanism $(x,t)$. Now we designate player 1 as the budget balancer and change his transfers in the following way $\tilde t_1(\theta)=t_1(\theta)-[-x(\theta)cI+\sum_{i=1}^I t_i(\theta)]+\mathbb{E}_{\theta_{-1}}[-x(\theta)cI+\sum_{i=1}^I t_i(\theta)|\theta_1]$

Note that -- given $\theta_1$ -- the expected value of the transfer did not change. In fact, player 1 is asked to cover the amount of the budget deficit that is above (or below) the budget deficit one would have expected conditional on player 1's type. Hence, $T_1$ and $U_1$ did not change and therefore participation constraint and incentive compatibility of player 1 still hold.

For player 2, modify transfers to $\tilde t_2(\theta)=t_2(\theta)-\mathbb{E}_{\theta_{-1}}[-x(\theta)cI+\sum_{i=1}^I t_i(\theta)|\theta_1]$. By ex ante budget balance, the expected value of $\mathbb{E}_{\theta_{-1}}[-x(\theta)cI+\sum_{i=1}^I t_i(\theta)|\theta_1]$ (taking expectation over $\theta_1$) is non-negative. As the term added does not involve $\theta_2$, incentive compatibility is not affected. Hence, $T_2$ and $U_2$ did not change and therefore participation constraint and incentive compatibility of player 2 still hold.

For all other players $\tilde t_i=t_i$. Adding all transfers then yields $\sum_i\tilde t_i(\theta)=x(\theta)cI$, i.e. ex post budget balance.
\end{footnotesize}
