#+Title: Signaling
#+AUTHOR:    Christoph Schottmüller
#+Date: 

#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport


#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: 
#+BEAMER_FRAME_LEVEL: 2
#+latex_header: \mode<beamer>{\useinnertheme{rounded}\usecolortheme{rose}\usecolortheme{dolphin}\setbeamertemplate{navigation symbols}{}\setbeamertemplate{footline}[frame number]{}}
#+latex_header: \mode<beamer>{\usepackage{amsmath}\usepackage{ae,aecompl}\usepackage{sgame,tikz}\usetikzlibrary{trees}}
#+LATEX_HEADER:\let\oldframe\frame\renewcommand\frame[1][allowframebreaks]{\oldframe[#1]}
#+LATEX_HEADER: \setbeamertemplate{frametitle continuation}[from second]

* Pirates

** Signaling example: Jolly Rodger

    \includegraphics[width=6cm]{jollyroger}

(story based on Leeson, "The invisible hook: the hidden economics of pirates", Princeton University Press, 2011)

** Pirate model
timing:  
   1. nature chooses attacker type: Pirate (P) with prob $p$ , commissioned (C) with $1-p$
   2. attacker chooses between Jolly Rodger (J) and other flag (F)
   3. defender decides whether to surrender (s) or fight (f)

Payoffs:
|           | Pirate (J or F) | commissioned (F) | commissioned (J) |
| /         | <               |                  |                  |
|-----------+-----------------+------------------+------------------|
| surrender | -1,3            | -1,3             |  -1,3-X          |
| fight     | -3,1            | 0,1              | 0,1-X            |


** Pirate analysis
|           | Pirate (J or F) | commissioned (F) | commissioned (J) |
| /         | <               |                  |                  |
|-----------+-----------------+------------------+------------------|
| surrender | -1,3            | -1,3             |  -1,3-X          |
| fight     | -3,1            | 0,1              | 0,1-X            |



- if $X\geq 2$, then "separating" equilibrium:
   - P play J
   - C play F
   - defender surrender iff J is played and fights otherwise

- if $X\in[0 ,2]$ and $p\leq 1/3$, then "hybrid" equilibrium:
   - P play J
   - C play J with prob $\lambda=2p/(1-p)$
   - defender surrenders against J with prob $\mu=X/2$ and with prob 0 against F

- if  $p\geq 1/3$, then "pooling" equilibrium
   - P and C mix between J and F in (roughly) the same proportion, e.g. always F
   - defender always surrenders

* Spence job market signaling
** Job market signaling
- worker has type $\theta\in\{\theta_l,\theta_h\}$ with $\theta_h>\theta_l>0$
- worker exerts effort $e$ at cost $c(e,\theta )$ with $c_e>0$, $c_{ee}>0$, $c(0,\theta)=0$ and $c_{e\theta }<0$
- 2 firms observe $e$ and simultaneously offer a wage
- worker takes higher offer (if $>0$)
- information
   - $\theta $ is worker's private information
   - firms view $\theta $ as being $\theta _h$ with probability $\lambda\in(0,1)$

- payoff worker $w-c(e,\theta)$
- payoff firm: $\theta-w$ (if offer accepted, 0 else)

** 2 Model interpretations
either
- 1 worker with privately known $\theta$ and 2 firms
- mass 1 of workers with share $\lambda$ of $\theta_h$ types, 2 or more firms

** Sequential equilibrium in job market signaling
- worker's strategy optimal given firms' strategy
- firms' belief $\mu(e)$ that worker is $\theta_h$ derived by Bayes rule wherever possible
- off equilibrium path choices of $e$:
   - firms have the same belief $\mu(e)$
- firms play Nash equilibrium given $\mu(e)$ (on and off path)

\vspace*{0.5cm}
- what are firms' equilibrium wage offers?

** Preliminaries
-  $\theta _h$ has flatter indifference curve than $\theta_l$ (single crossing)
- wage $w(e) \in[\theta_l,\theta_h]$

** Separating equilibria I
- separating: two types have different effort choices
*** Lemma							    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
In a separating equilibrium, $w(e(\theta_l))=\theta_l$ and $w(e(\theta_h))=\theta_h$. Furthermore, $e(\theta_l)=0$.

*** 							    :B_ignoreheading:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :END:

- what effort levels are possible for $\theta_h$ in a separating equilibrium?

\begin{tikzpicture}[scale=3] 
\draw [<->](0,1) -- (0,0) -- (1,0) ;
\node[left] at (0,1){$w$};
\node[right] at (1,0){$e$};
\node[left]  at (0,.8) {$\theta_h$};
\draw[dashed] (0,0.8)--(1,0.8);
\node[left]  at (0,.2) {$\theta_l$};
\draw[dashed] (0,0.2)--(1,0.2);
\draw[blue,thick,domain=0:0.46] plot(\x,{3*\x^2+0.2});
\draw[red,thick,domain=0:0.85] plot(\x,{.9*\x^2+0.2});
\node[below] at (0.44,0) {$\tilde e$};
\node[below] at (0.81,0) {$\bar e$};
\node[below,red] at (0.81,1.02) {$\bar u(\theta_h)$};
\node[below,blue] at (0.44,1.03) {$\bar u(\theta_l)$};
\draw[help lines,dashed] (0.44,0.0)--(0.44,.8);
\draw[help lines,dashed] (0.81,0.0)--(0.81,.8);
\end{tikzpicture}

** Separating equilibria II

- what kind of beliefs (i.e. wage offers) sustain such an equilibrium?

\begin{tikzpicture}[scale=3] 
\draw [<->](0,1) -- (0,0) -- (1,0) ;
\node[left] at (0,1){$w$};
\node[right] at (1,0){$e$};
\node[left]  at (0,.8) {$\theta_h$};
\draw[dashed] (0,0.8)--(1,0.8);
\node[left]  at (0,.2) {$\theta_l$};
\draw[dashed] (0,0.2)--(1,0.2);
\draw[blue,thick,domain=0:0.47] plot(\x,{3*\x^2+0.2});
\draw[red,thick,domain=0:0.85] plot(\x,{.9*\x^2+0.2});
\node[below] at (0.44,0) {$\tilde e$};
\node[below] at (0.81,0) {$\bar e$};
%\node[below,red] at (0.81,1.02) {$\bar u(\theta_h)$};
%\node[below,blue] at (0.44,1.03) {$\bar u(\theta_l)$};
%\draw[help lines,dashed] (0.44,0.0)--(0.44,.8);
%\draw[help lines,dashed] (0.81,0.0)--(0.81,.8);
\draw[red,thick,domain=0:0.7] plot(\x,{.9*\x^2+0.4});
\node[below] at (0.66,0) {$e^*$};
\draw[help lines,dashed] (0.66,0.0)--(0.66,.8);
\draw[black,thick] (0,0.2)--(0.3,0.2)--(0.4,0.45)--(0.5,0.35)--(0.667,0.8)--(0.99,0.7);
\node[right] at (0.99,0.7){$w(e)$};
\end{tikzpicture}
- $\mu(e)=(w(e)-\theta_l)/(\theta_h-\theta_l)\in[0,1]$

- among separating equilibria, which are Pareto efficient?
# $e^*=\tilde e$

** Pooling equilibria I

- pooling: both types exert same effort level $e^*$
- $\mu(e^*)=\lambda$ and $w(e^*)=\mathbb{E}[\theta]=\lambda\theta_h+(1-\lambda)\theta_l$
- which effort levels can be sustained in a pooling equilibrium?
\begin{tikzpicture}[scale=3] 
\draw [<->](0,1) -- (0,0) -- (1,0) ;
\node[left] at (0,1){$w$};
\node[right] at (1,0){$e$};
\node[left]  at (0,.8) {$\theta_h$};
\draw[dashed] (0,0.8)--(1,0.8);
\node[left]  at (0,.2) {$\theta_l$};
\draw[dashed] (0,0.2)--(1,0.2);
\node[left] at (0,0.55) {$\mathbb{E}[\theta]$};
\draw[dashed] (0,0.55)--(1,0.55);
\draw[blue,thick,domain=0:0.46] plot(\x,{3*\x^2+0.2});
\draw[red,thick,domain=0:0.85] plot(\x,{.9*\x^2+0.2});
\node[below] at (0.44,0) {$\tilde e$};
\node[below] at (0.81,0) {$\bar e$};
\node[below] at (0.34,0) {$e'$};
\node[below,red] at (0.81,1.02) {$\bar u(\theta_h)$};
\node[below,blue] at (0.44,1.03) {$\bar u(\theta_l)$};
\draw[help lines,dashed] (0.44,0.0)--(0.44,.8);
\draw[help lines,dashed] (0.81,0.0)--(0.81,.8);
\draw[help lines,dashed] (0.34,0.0)--(0.34,.8);
\end{tikzpicture}
# any between 0 and e'

** Pooling equilibria II
\begin{tikzpicture}[scale=3] 
\draw [<->](0,1) -- (0,0) -- (1,0) ;
\node[left] at (0,1){$w$};
\node[right] at (1,0){$e$};
\node[left]  at (0,.8) {$\theta_h$};
\draw[dashed] (0,0.8)--(1,0.8);
\node[left]  at (0,.2) {$\theta_l$};
\draw[dashed] (0,0.2)--(1,0.2);
\node[left] at (0,0.55) {$\mathbb{E}[\theta]$};
\draw[dashed] (0,0.55)--(1,0.55);
\draw[blue,thick,domain=0:0.46] plot(\x,{3*\x^2+0.4});
\draw[red,thick,domain=0:0.7] plot(\x,{.9*\x^2+0.505});
%\node[below] at (0.36,0) {$e'$};
\node[below] at (0.22,0) {$e^*$};
%\node[below,red] at (0.81,1.02) {$\bar u(\theta_h)$};
%\node[below,blue] at (0.44,1.03) {$\bar u(\theta_l)$};
%\draw[help lines,dashed] (0.44,0.0)--(0.44,.8);
\draw[help lines,dashed] (0.225,0.0)--(0.225,.8);
%\draw[help lines,dashed] (0.34,0.0)--(0.34,.8);
\draw[black,thick] (0,0.2)--(0.1,0.3)--(0.225,0.55)--(0.4,0.5)--(0.667,0.7)--(0.99,0.75);
\node[right] at (0.99,0.75){$w(e)$};
\end{tikzpicture}

** Welfare
- what is equilibrium without signaling possibility?
- who is better/worse off due to signaling possibility?
# note depending on $\lambda$ and $c$, even high types can be worse off in separating; e.g. if $\lambda$ is sufficiently high and E[\theta] therefore close to \theta_h


** Refinements I
- multiplicity of equilibria supported by off path beliefs that can be freely chosen
- are these beliefs reasonable?

\begin{tikzpicture}[scale=3] 
\draw [<->](0,1) -- (0,0) -- (1,0) ;
\node[left] at (0,1){$w$};
\node[right] at (1,0){$e$};
\node[left]  at (0,.8) {$\theta_h$};
\draw[dashed] (0,0.8)--(1,0.8);
\node[left]  at (0,.2) {$\theta_l$};
\draw[dashed] (0,0.2)--(1,0.2);
\draw[blue,thick,domain=0:0.47] plot(\x,{3*\x^2+0.2});
\draw[red,thick,domain=0:0.85] plot(\x,{.9*\x^2+0.2});
%\node[below] at (0.44,0) {$\tilde e$};
%\node[below] at (0.81,0) {$\bar e$};
%\node[below,red] at (0.81,1.02) {$\bar u(\theta_h)$};
%\node[below,blue] at (0.44,1.03) {$\bar u(\theta_l)$};
%\draw[help lines,dashed] (0.44,0.0)--(0.44,.8);
%\draw[help lines,dashed] (0.81,0.0)--(0.81,.8);
\draw[red,thick,domain=0:0.7] plot(\x,{.9*\x^2+0.4});
\node[below] at (0.66,0) {$e^*$};
\draw[help lines,dashed] (0.66,0.0)--(0.66,.8);
\draw[black,thick] (0,0.2)--(0.3,0.2)--(0.4,0.45)--(0.5,0.35)--(0.667,0.8)--(0.99,0.7);
\node[right] at (0.99,0.7){$w(e)$};
\end{tikzpicture}

** Refinements: dominance 
- rule out beliefs that are based on some type taking a dominated action
  - if action $a'$ is 
     - off path, 
     - strictly dominated for type $\theta'$, i.e. no matter what strategy other players have there is another action $a''$ which is strictly better for type $\theta'$, 
     - not strictly dominated for type $\theta''$
  - then belief after observing $a'$ should not assign positive probability to type $\theta'$

- no effort level in job market signaling is strictly dominated

** Refinements: equilibrium dominance
- "equilibrium domination"
   - if the deviation leads to a lower payoff for type $\theta'$ than his equilibrium payoff no matter what belief it induces  (but not necessarily so for $\theta''$) then belief should assign 0 to $\theta'$
   - effort level between $\tilde e$ and $\bar e$ should lead to $\mu(e)=1$
   - which separating equilibria satisfy this?
   - what about pooling equilibria?
# only least cost separating survives!

** Refinements: intuitive criterion

- $S^*$: set of equilibrium choices (i.e. wage offers) given some arbitrary belief
 # - in our game: $S^*=[\theta_l,\theta_h]$
- $\Theta^{**}(e)$: set of types that could potentially gain by deviation given that wage offers are in $S^*$ (if induced belief is sufficiently favorable), i.e. types such that
$$u^*(\theta)\leq \max_{w\in S^*}u(e,w,\theta)$$
#   - in our game and separating eq.: $\Theta^{**}(e)=\{\theta_h\}$ for $e>\tilde e$ 
- $S^{**}(e)$: set of equilibrium choices (i.e. wage offers) given that the firms' common belief puts only positive probability on types in $\Theta^{**}(e)$
#   - in our game and separating eq.: $S^{**}(e)=\{\theta_h\}$  for $e>\tilde e$ 
- an equilibrium /fails the intuitive criterion/ if there is a type $\theta$ and an action $a$ such that 
$$u^*(\theta)<\min_{s\in S^{**}}u(e,w,\theta)$$
#   - in our game: and separating eq. with $e^*>\tilde e$: fail intuitive criterion as $\theta_h$'s eq. payoff is lower than a deviation to $(e^*+\tilde e)/2$ 

